# Generated by Django 3.2.9 on 2021-11-05 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='upload/')),
                ('level', models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_games', models.IntegerField(default=0)),
                ('winrate', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('WIN', 'Win'), ('LOSE', 'Lose'), ('TIE', 'Tie')], max_length=5, null=True)),
                ('board1', models.CharField(max_length=1)),
                ('board2', models.CharField(max_length=1)),
                ('board3', models.CharField(max_length=1)),
                ('board4', models.CharField(max_length=1)),
                ('board5', models.CharField(max_length=1)),
                ('board6', models.CharField(max_length=1)),
                ('board7', models.CharField(max_length=1)),
                ('board8', models.CharField(max_length=1)),
                ('board9', models.CharField(max_length=1)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bot')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
