# Generated by Django 3.2.9 on 2021-11-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_player_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='upload/bot/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='upload/player/'),
        ),
    ]
