# Generated by Django 3.2.9 on 2021-11-06 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_player_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bot'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.player'),
        ),
    ]
