# Generated by Django 3.2.9 on 2021-11-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20211106_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='total_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bot',
            name='total_lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bot',
            name='total_tie',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bot',
            name='total_win',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bot',
            name='win_rate',
            field=models.FloatField(default=0),
        ),
    ]
