# Generated by Django 3.2.9 on 2021-11-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20211107_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_play',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
