# Generated by Django 3.2.9 on 2021-11-08 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_game_player_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.player'),
        ),
    ]
