# Generated by Django 3.2.9 on 2021-11-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_game_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/bot/'),
        ),
    ]
